language: go
sudo: false
go:
    - tip
install:
    - go get github.com/satori/go.uuid
    - go get github.com/garyburd/redigo/redis
services:
    - redis
matrix:
    allow_failures:
        - go: tip
after_success:
    - coveralls
